def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'hello.cpp',
        target = 'hello',
	use = ['SPTK'], # if you use local library
#	lib = ['SPTK'], # if you use installed library
        includes = ['../include']) # SPTK.h


        
